%{
/* generated by bison */
#include "parser.tab.h"
extern int atoi (const char *);
%}

%option noyywrap

%%

[0-9]+	{ yylval.ival = atoi(yytext); return NUMBER; }
[\n\t ]+	/*skip whitechars*/
"sum_odd" { return SUM_ODD; }
"sum_even" { return SUM_EVEN; }
"size"	{ return SIZE; }
"ignore" { return IGNORE; }
"("	{ return '('; }
")"	{ return ')'; }
.	{ printf("unrecognized token %c\n", yytext[0]); }

%%